Add `InsecureTLS` field for `S3` backend storage
kubestash/apimachinery pull request #100
Opened 2024-01-31 09:45 UTC by anisurrahman75

2024-01-31 14:07 UTC, hmsayem submitted a review, later dismissed

2024-02-01 04:02 UTC, ishtiaqhimel requested changes

2024-02-01 04:02 UTC, ishtiaqhimel commented on apis/storage/v1alpha1/types.go
> +	// When InsecureSkipVerify is set to true in a TLS configuration,
`When InsecureSkipVerify is set` -> `When InsecureTLS is set`

2024-02-01 11:54 UTC, ishtiaqhimel approved these changes

2024-02-01 12:19 UTC, hmsayem approved these changes

2024-02-01 12:19 UTC, merged