Add `Namespace` field into `restoiresession.datasource` for cross namespace restore
kubestash/apimachinery pull request #104
Opened 2024-02-28 10:16 UTC by anisurrahman75

Signed-off-by: Anisur Rahman <anisur@appscode.com>

2024-02-29 12:07 UTC, ishtiaqhimel requested changes

2024-02-29 12:07 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_types.go
> +	// Namespace specifies the Namespace name where the DataSource i.e (Repository, Snapshots) exists.
DataSource (i.e. Repository, Snapshot) exists.

2024-02-29 12:07 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_types.go
> +	Namespace string `json:"namespace,omitempty,omitempty"`
Namespace string `json:"namespace,omitempty"`

2024-03-05 15:58 UTC, ishtiaqhimel requested changes

2024-03-05 15:58 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_types.go
> +	// Namespace specifies the Namespace name where the DataSource i.e (Repository, Snapshots) exists.
Namespace specifies the namespace of the DataSource (i.e. Repository, Snapshot).

2024-03-11 05:58 UTC, ishtiaqhimel approved these changes

2024-03-12 06:11 UTC, hmsayem approved these changes

2024-03-12 06:17 UTC, merged