Add `availableVersions` field in Function; Resolve addon dynamically
kubestash/apimachinery pull request #110
Opened 2024-04-22 09:18 UTC by ArnobKumarSaha

2024-04-22 10:28 UTC, hmsayem submitted a review, later dismissed

2024-04-23 05:56 UTC, ishtiaqhimel requested changes

2024-04-23 05:56 UTC, ishtiaqhimel commented on pkg/version.go
> +	})
```go
sort.Slice(distances, func(i, j int) bool {
	if distances[i].minor != distances[j].minor {
		return distances[i].minor < distances[j].minor
	}
	if distances[i].patch != distances[j].patch {
		return distances[i].patch < distances[j].patch
	}
	return distances[i].isDB < distances[j].isDB
})
```

We can make it less nested.

2024-04-23 05:56 UTC, ishtiaqhimel commented on pkg/version.go
> +	return "", fmt.Errorf("no addon versions found for db version %s", dbVersion)
no addon versions -> no addon version

2024-04-23 05:56 UTC, ishtiaqhimel commented on pkg/version.go
> +		return "", fmt.Errorf("no addon versions found with major=%v for db version %s", semverDBVersion.Major(), dbVersion)
no addon versions -> no addon version

2024-04-23 06:56 UTC, ishtiaqhimel approved these changes

2024-04-26 13:17 UTC, anisurrahman75 approved these changes

2024-04-27 08:32 UTC, merged