Add necessary fields for separately retention policy applier
kubestash/apimachinery pull request #111
Opened 2024-05-27 11:50 UTC by anisurrahman75

2024-06-11 13:29 UTC, ishtiaqhimel requested changes

2024-06-12 12:35 UTC, anisurrahman75 commented on apis/storage/v1alpha1/snapshot_types.go
> +	// Duration represents the amount of time it took to complete the backup process.
Yes.
This cmd is already inside `walGStats`. Do you think it's necessary to add again driver info here?

2024-06-12 12:42 UTC, anisurrahman75 commented on pkg/snapshots_cleanup/common.go
> +	staleSnapshotsFile        = apis.TempDirMountPath + "/" + "stale_snapshots_by_repo.json"
We can't dechlare constant with `filepath.join`. cause it returns string. 
That case instead of constant we have to use `var`.

2024-06-12 13:05 UTC, ishtiaqhimel commented on apis/storage/v1alpha1/snapshot_types.go
> +	// Duration represents the amount of time it took to complete the backup process.
We should remove this `Duration` field and use the `Duration` field specified inside `Component`.

2024-06-12 13:09 UTC, ishtiaqhimel commented on pkg/snapshots_cleanup/common.go
> +	staleSnapshotsFile        = apis.TempDirMountPath + "/" + "stale_snapshots_by_repo.json"
Use `const`. Only keep the file name.

2024-06-12 13:47 UTC, ishtiaqhimel submitted a review, later dismissed

2024-06-14 10:12 UTC, hmsayem requested changes

2024-06-14 10:12 UTC, hmsayem commented on pkg/snapshots_cleanup/common.go
> +	retentionPolicyStatusFilePath = apis.TempDirMountPath + "/retention_policy_status_by_repo.json"
```suggestion
	pruneErrorsFilePath = apis.TempDirMountPath + "/prune_errors_by_repo.json"
```

2024-06-14 10:12 UTC, hmsayem commented on pkg/snapshots_cleanup/common.go
> +	byteData, err := os.ReadFile(retentionPolicyStatusFilePath)
```suggestion
	bytes, err := os.ReadFile(retentionPolicyStatusFilePath)
```

2024-06-14 10:18 UTC, hmsayem requested changes

2024-06-14 10:18 UTC, hmsayem commented on pkg/snapshots_cleanup/common.go
> +	pruneStatus, err := FetchPruneStatusByRepo()
```suggestion
	pruneErrors, err := FetchPruneStatusByRepo()
```

2024-06-14 12:01 UTC, hmsayem requested changes

2024-06-14 12:01 UTC, hmsayem commented on pkg/snapshots_cleanup/common.go
> +package snapshotscleanup
```suggestion
package snapshot
```

2024-06-14 12:01 UTC, hmsayem commented on pkg/snapshots_cleanup/common.go
> +package snapshotscleanup
file: snapshot.go

2024-06-25 10:33 UTC, hmsayem commented on pkg/snapshot/snapshot.go
> +	if err := createFileIfNotExists(staleSnapshotsFilePath); err != nil {
InitStaleSnapshotListFile

2024-06-25 11:10 UTC, hmsayem requested changes

2024-06-26 06:18 UTC, ishtiaqhimel approved these changes

2024-06-26 12:25 UTC, hmsayem approved these changes

2024-06-26 12:27 UTC, merged