Add druid manifest backup
kubestash/apimachinery pull request #124
Opened 2024-08-12 13:03 UTC by tapojit047

2024-08-12 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubestash/apimachinery?pullRequest=124) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubestash/apimachinery?pullRequest=124) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubestash/apimachinery?pullRequest=124) it.</sub>

2024-09-04 06:09 UTC, ishtiaqhimel requested changes

2024-09-04 06:09 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_types.go
> +	// Name and namespace of the dependency
Update this comment "Name specifies the restored name of the corresponding dependency"

2024-09-04 06:09 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_types.go
> +	// If the dependency is externally managed,
Restore specifies whether to restore dependency manifest or not if the dependency is externally managed

2024-09-04 10:41 UTC, ishtiaqhimel approved these changes

2024-09-12 09:49 UTC, hmsayem approved these changes

2024-09-16 04:37 UTC, hmsayem approved these changes

2024-09-16 04:38 UTC, merged