Add constants for initial backup trigger
kubestash/apimachinery pull request #127
Opened 2024-08-29 12:20 UTC by anisurrahman75

2024-08-29 12:51 UTC, hmsayem requested changes

2024-08-29 12:51 UTC, hmsayem commented on apis/core/v1alpha1/backupconfiguration_types.go
> +	ReasonInitialBackupTriggered    = "ReasonInitialBackupTriggered"
```suggestion
	// TypeInitialBackupTriggered indicates whether the backup is triggered or not.
	TypeInitialBackupTriggered      = "InitialBackupTriggered"
	ReasonFailedToTriggerInitialBackup = "FailedToTriggerInitialBackup"
	ReasonSuccessfullyTriggeredInitialBackup    = "SuccessfullyTriggeredInitialBackup"
```

2024-08-29 13:07 UTC, ishtiaqhimel requested changes

2024-08-29 13:07 UTC, ishtiaqhimel commented on apis/core/v1alpha1/backupconfiguration_types.go
> +	// TypeInitialBackupTriggered indicates whether the backup is triggered or not.
// TypeInitialBackupTriggered indicates whether the initial backup is triggered or not.

2024-08-30 04:52 UTC, hmsayem approved these changes

2024-08-30 04:52 UTC, merged