Add supportive function for kubedb `restoring` phase
kubestash/apimachinery pull request #133
Opened 2024-09-19 10:23 UTC by anisurrahman75

2024-09-21 16:56 UTC, ishtiaqhimel requested changes

2024-09-21 16:56 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_helpers.go
> +func (rs *RestoreSession) GetTargetObjectRef(snap *v1alpha1.Snapshot) *kmapi.ObjectReference {
This won't work if multiple options are provided.

2024-09-23 10:00 UTC, tapojit047 requested changes

2024-09-23 10:00 UTC, tapojit047 commented on apis/core/v1alpha1/restoresession_helpers.go
> +	return &objRef
Return `Target *kmapi.TypedObjectReference` instead of `*kmapi.ObjectReference`

2024-09-23 10:38 UTC, ishtiaqhimel requested changes

2024-09-23 10:38 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_helpers.go
> +				Namespace: opt.MySQL.RestoreNamespace,
This can cause panic if user provides wrong manifest option

2024-09-23 10:38 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_helpers.go
> +	}
Add check for Elasticsearch

2024-09-23 10:42 UTC, ishtiaqhimel reviewed
```go
func (rs *RestoreSession) getRestoreNamespacedName(targetKind string) *types.NamespacedName {
	if rs.Spec.ManifestOptions == nil {
		return &types.NamespacedName{}
	}

	optionsMap := map[string]func() (string, string){
		apis.KindMySQL: func() (string, string) {
			if rs.Spec.ManifestOptions.MySQL != nil {
				return rs.Spec.ManifestOptions.MySQL.DBName, rs.Spec.ManifestOptions.MySQL.RestoreNamespace
			}
			return "", ""
		},
		apis.KindPostgres: func() (string, string) {
			if rs.Spec.ManifestOptions.Postgres != nil {
				return rs.Spec.ManifestOptions.Postgres.DBName, rs.Spec.ManifestOptions.Postgres.RestoreNamespace
			}
			return "", ""
		},
		apis.KindMongoDB: func() (string, string) {
			if rs.Spec.ManifestOptions.MongoDB != nil {
				return rs.Spec.ManifestOptions.MongoDB.DBName, rs.Spec.ManifestOptions.MongoDB.RestoreNamespace
			}
			return "", ""
		},
		apis.KindMariaDB: func() (string, string) {
			if rs.Spec.ManifestOptions.MariaDB != nil {
				return rs.Spec.ManifestOptions.MariaDB.DBName, rs.Spec.ManifestOptions.MariaDB.RestoreNamespace
			}
			return "", ""
		},
		apis.KindRedis: func() (string, string) {
			if rs.Spec.ManifestOptions.Redis != nil {
				return rs.Spec.ManifestOptions.Redis.DBName, rs.Spec.ManifestOptions.Redis.RestoreNamespace
			}
			return "", ""
		},
		apis.KindMSSQLServer: func() (string, string) {
			if rs.Spec.ManifestOptions.MSSQLServer != nil {
				return rs.Spec.ManifestOptions.MSSQLServer.DBName, rs.Spec.ManifestOptions.MSSQLServer.RestoreNamespace
			}
			return "", ""
		},
		apis.KindDruid: func() (string, string) {
			if rs.Spec.ManifestOptions.Druid != nil {
				return rs.Spec.ManifestOptions.Druid.DBName, rs.Spec.ManifestOptions.Druid.RestoreNamespace
			}
			return "", ""
		},
		apis.KindZooKeeper: func() (string, string) {
			if rs.Spec.ManifestOptions.ZooKeeper != nil {
				return rs.Spec.ManifestOptions.ZooKeeper.DBName, rs.Spec.ManifestOptions.ZooKeeper.RestoreNamespace
			}
			return "", ""
		},
		apis.KindSinglestore: func() (string, string) {
			if rs.Spec.ManifestOptions.Singlestore != nil {
				return rs.Spec.ManifestOptions.Singlestore.DBName, rs.Spec.ManifestOptions.Singlestore.RestoreNamespace
			}
			return "", ""
		},
	}

	if getOpts, ok := optionsMap[targetKind]; ok {
		dbName, namespace := getOpts()
		return &types.NamespacedName{
			Name:      dbName,
			Namespace: namespace,
		}
	}

	return &types.NamespacedName{}
}
```

2024-09-24 05:59 UTC, ishtiaqhimel approved these changes

2024-09-25 06:09 UTC, merged