Add Stdin Backup Leaf Command support
kubestash/apimachinery pull request #140
Opened 2024-11-12 06:36 UTC by anisurrahman75

2024-11-26 09:47 UTC, ishtiaqhimel submitted a review, later dismissed

2025-01-02 09:49 UTC, hmsayem requested changes

2025-01-02 09:49 UTC, hmsayem commented on pkg/restic/backup.go
> +func (w *ResticWrapper) RunBackup(backupOption BackupOptions) ([]*BackupOutput, error) {
```suggestion
func (w *ResticWrapper) RunBackup(backupOption BackupOptions) ([]BackupOutput, error) {
```

2025-01-02 09:49 UTC, hmsayem commented on pkg/restic/backup.go
> +func (w *ResticWrapper) RunParallelBackup(backupOptions []BackupOptions, maxConcurrency int) ([]*[]*BackupOutput, error) {
```suggestion
func (w *ResticWrapper) RunParallelBackup(backupOptions []BackupOptions, maxConcurrency int) ([][]BackupOutput, error) {
```

2025-01-03 05:59 UTC, ishtiaqhimel submitted a review, later dismissed
If we don't need shared mutability then use `[]anything` otherwise use `[]*anything`.

cc: @anisurrahman75 @hmsayem

2025-01-08 08:37 UTC, hmsayem requested changes

2025-01-08 08:37 UTC, hmsayem commented on pkg/restic/backup.go
> +	var multipleOutputs [][]BackupOutput
```suggestion
	var multiBackendBackupOutputs [][]BackupOutput
```

2025-01-08 09:10 UTC, hmsayem commented on pkg/restic/backup.go
> +}
Fix timeout setting.

2025-01-23 12:27 UTC, merged