Add backend cleanup feature
kubestash/apimachinery pull request #36
Opened 2023-07-07 04:12 UTC by anisurrahman75

Signed-off-by: anisurrahman75 <sunny.cse7575@gmail.com>

2023-07-24 09:17 UTC, hmsayem requested changes

2023-07-24 09:17 UTC, hmsayem commented on apis/constant.go
> +	KubeStashBackendCleanupJobClusterRole = "kubestash-BackendCleanup-job"
`KubeStashLocalBackendJobClusterRole   = "kubestash-local-backend-job"`
`KubeStashBackendCleanerJobClusterRole = "kubestash-backend-cleaner-job"`

2023-07-24 09:17 UTC, hmsayem commented on apis/storage/v1alpha1/backupstorage_types.go
> +	// Job holds the cleanup jobs Information that's created regarding this BackupStorage
// Job holds the cleaner jobs information for this BackupStorage

2023-07-24 09:17 UTC, hmsayem commented on apis/storage/v1alpha1/repository_types.go
> +	// Job holds the cleanup jobs Information that's created regarding this Repository
// Job holds the cleaner jobs information for this repository

2023-07-24 09:17 UTC, hmsayem commented on apis/storage/v1alpha1/snapshot_helpers.go
>  func (s *Snapshot) CalculatePhase() SnapshotPhase {
```go
func (s *Snapshot) CalculatePhase() SnapshotPhase {
	if kmapi.IsConditionFalse(s.Status.Conditions, TypeSnapshotMetadataUploaded) ||
		kmapi.IsConditionFalse(s.Status.Conditions, TypeRecentSnapshotListUpdated) {
		return SnapshotFailed
	}
	
	if s.GetComponentsPhase() == SnapshotPending {
		return SnapshotPending
	}
	
	if kmapi.HasCondition(s.Status.Conditions, TypeSnapshotMetadataUploaded) {
		return s.GetComponentsPhase()
	}
	
	return  SnapshotRunning
}
```

2023-07-25 07:04 UTC, hmsayem requested changes

2023-07-25 07:04 UTC, hmsayem commented on apis/storage/v1alpha1/backupstorage_types.go
> +	Job string `json:"job,omitempty"`
`Job` -> `cleanerJob`

2023-07-25 07:04 UTC, hmsayem commented on apis/storage/v1alpha1/repository_types.go
> +	Job string `json:"job,omitempty"`
`Job` -> `cleanerJob`

2023-07-25 07:04 UTC, hmsayem commented on apis/variables.go
> +	Name           = "name"
remove this variable

2023-07-25 12:36 UTC, hmsayem requested changes

2023-07-25 12:36 UTC, hmsayem commented on apis/storage/v1alpha1/snapshot_helpers.go
> +	newLabels[apis.KubeStashInvokerKind] = ResourceKindBackupStorage
`ResourceKindSnapshot`

2023-07-25 12:36 UTC, hmsayem commented on apis/storage/v1alpha1/repository_types.go
> +	CleanerJob string `json:"cleanerJob,omitempty"`
add `invokerKind` label  repoisotry

2023-07-28 10:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubestash/apimachinery?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubestash/apimachinery?pullRequest=36) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubestash/apimachinery?pullRequest=36) it.</sub>

2023-07-28 11:34 UTC, hmsayem approved these changes

2023-07-28 11:35 UTC, ishtiaqhimel approved these changes

2023-07-28 11:37 UTC, merged