Update RestoreSession webhook for the PITR feature
kubestash/apimachinery pull request #64
Opened 2023-10-25 06:13 UTC by anisurrahman75

Signed-off-by: Anisur Rahman <anisur@appscode.com>

2023-10-25 06:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubestash/apimachinery?pullRequest=64) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubestash/apimachinery?pullRequest=64) before we can accept your contribution.<br/><hr/>**Anisur Rahman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubestash/apimachinery?pullRequest=64) it.</sub>

2023-11-02 05:52 UTC, ishtiaqhimel requested changes

2023-11-02 05:52 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_types.go
>  	// +kubebuilder:validation:Format=date-time
Do we need to validate if we use `*metav1.Time`?

2023-11-02 05:52 UTC, ishtiaqhimel commented on apis/core/v1alpha1/restoresession_webhook.go
> +		return fmt.Errorf("TargetTime can not be nil for the Point-In-Time Recovery (PITR) feature")
1. `TargetTime` -> `targetTime`
2. `nil` -> `empty`

2023-11-02 06:14 UTC, ishtiaqhimel approved these changes

2023-11-02 06:49 UTC, hmsayem requested changes

2023-11-02 07:02 UTC, hmsayem approved these changes

2023-11-03 04:43 UTC, hmsayem approved these changes

2023-11-07 05:11 UTC, hmsayem approved these changes

2023-11-09 04:55 UTC, merged