export ```convertSizeToByte``` function
kubestash/apimachinery pull request #77
Opened 2023-11-13 13:08 UTC by anisurrahman75

Signed-off-by: Anisur Rahman <anisur@appscode.com>

2023-11-13 13:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubestash/apimachinery?pullRequest=77) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubestash/apimachinery?pullRequest=77) before we can accept your contribution.<br/><hr/>**Anisur Rahman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubestash/apimachinery?pullRequest=77) it.</sub>

2023-11-15 04:52 UTC, ishtiaqhimel approved these changes

2023-11-15 04:54 UTC, ishtiaqhimel commented on apis/storage/v1alpha1/snapshot_helpers.go
> +		return 0, fmt.Errorf("for snapshots %s/%s Status components is empty", s.Namespace, s.Name)
"no component found for snapshot %s/%s"

2023-11-15 04:55 UTC, ishtiaqhimel commented on apis/storage/v1alpha1/snapshot_helpers.go
> +				return 0, fmt.Errorf("resticStats size of component %s of the snapshots %s/%s is empty", s.Namespace, s.Name, componentName)
resticStats size of component %s is empty for the snapshot %s/%s

2023-11-15 04:56 UTC, ishtiaqhimel commented on apis/storage/v1alpha1/snapshot_helpers.go
> +				return 0, fmt.Errorf("resticStats size unit of component %s of the snapshots %s/%s is invalid", s.Namespace, s.Name, componentName)
resticStats size of component %s is invalid for the snapshot %s/%s

2023-11-15 05:57 UTC, ishtiaqhimel submitted a review, later dismissed

2023-11-22 07:16 UTC, hmsayem requested changes

2023-11-22 15:55 UTC, hmsayem approved these changes

2023-11-22 15:56 UTC, hmsayem approved these changes

2023-11-22 15:57 UTC, merged