Add snapshot labels for label selector support
kubestash/apimachinery pull request #78
Opened 2023-11-22 05:26 UTC by anisurrahman75

Signed-off-by: Anisur Rahman <anisur@appscode.com>

2023-11-22 05:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubestash/apimachinery?pullRequest=78) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubestash/apimachinery?pullRequest=78) before we can accept your contribution.<br/><hr/>**Anisur Rahman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubestash/apimachinery?pullRequest=78) it.</sub>

2023-11-23 09:37 UTC, ishtiaqhimel submitted a review, later dismissed

2023-11-23 10:02 UTC, hmsayem requested changes

2023-11-23 10:02 UTC, hmsayem commented on apis/constant.go
> +	KubeStashRepositoryName = "kubestash.com/repository-name"
`repository-name` -> `repo-name`

2023-11-23 11:11 UTC, ishtiaqhimel submitted a review, later dismissed

2023-11-23 12:24 UTC, hmsayem requested changes

2023-11-23 12:24 UTC, hmsayem commented on apis/constant.go
add:
ComponentVolumeSnapshots = "volumesnapshots"

2023-11-23 12:44 UTC, merged