Add constant `KubeStashPopulatorJobClusterRole` for role binding support
kubestash/apimachinery pull request #99
Opened 2024-01-24 06:24 UTC by anisurrahman75

Signed-off-by: Anisur Rahman <anisur@appscode.com>

2024-01-24 08:37 UTC, ishtiaqhimel submitted a review, later dismissed

2024-01-24 10:21 UTC, hmsayem approved these changes

2024-01-24 17:23 UTC, hmsayem requested changes

2024-01-24 17:23 UTC, hmsayem commented on apis/constant.go
>  	KubeStashBackendAccessorClusterRole = "kubestash-backend-accessor"
Remove KubeStashBackendAccessorClusterRole and Use KubeStashNetVolAccessor

2024-01-25 12:25 UTC, ishtiaqhimel approved these changes

2024-01-31 11:15 UTC, hmsayem submitted a review, later dismissed

2024-02-01 12:22 UTC, hmsayem approved these changes

2024-02-01 12:37 UTC, hmsayem approved these changes

2024-02-01 13:04 UTC, merged